# Start from node.js v12
FROM cypress/base
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
COPY yarn.lock ./

# Install node libraries
RUN yarn install

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

# Expose port 3000
EXPOSE 3000

# Initialize database with migrations
RUN yarn run prisma
# build app
RUN yarn run nexus:build
RUN yarn run build
# Start app in the background
RUN yarn run start &
## RUN npx prisma migrate up --experimental
CMD [ "yarn", "run", "test"]


