# Start from node.js v12
FROM cypress/base
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
COPY yarn.lock ./

# Install node libraries
RUN yarn install

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

# Expose port 3000
EXPOSE 3000

RUN echo "WHERE IS THE DB URL: $DATABASE_URL"
RUN echo "CYPRESS KEY: $CYPRESS_RECORD_KEY"
# Initialize database with migrations
RUN yarn run prisma
# Run cypress tests
CMD [ "yarn", "run", "test"]


