# docker-compose-test.yml
version: "3.8"
services:
  sut:
    image: "cypress/included:13.2.0"
    container_name: "app"
    env_file: ".env"
    environment:
      - DATABASE_URL=postgres://voty:voty@postgres:5432/voty
      - CYPRESS_RECORD_KEY # pass on from GitHub-Actions or cmdline
      - GITHUB_TOKEN # pass on from GitHub-Actions or cmdline
      - NODE_ENV=test
      - PORT=3000
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      - postgres
    links:
      - postgres
    volumes:
      - .:/usr/src/app
    expose:
      - "3000"
    working_dir: "/usr/src/app"
    entrypoint: ["yarn", "run", "ci:test"]

  postgres:
    image: "postgres:13-alpine"
    container_name: "postgres"
    expose:
      - "5432"
    environment:
      POSTGRES_USER: voty
      POSTGRES_PASSWORD: voty
      POSTGRES_DB: voty
