FROM node:24
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
COPY yarn.lock ./

# Install node libraries
RUN yarn install

# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

# Expose port 3000
EXPOSE 3000

# Generate prisma typescript schema
RUN npx prisma generate
## RUN npx prisma migrate up --experimental
CMD [ "yarn", "run", "dev"]


