---
- name: reload user systemd
  systemd:
    daemon_reload: yes
    scope: user
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"

- name: restart voty
  systemd:
    name: voty
    scope: user
    state: restarted
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"
