---
- name: Build Docker Image
  block:
    - name: Build Docker Image
      docker_image:
        name: "voty-web"
        source: "build"
        force_source: "yes"
        build:
          pull: "no"
          path: "{{app_dir}}"
