---
- name: Pull and Deploy Docker Image
  block:
    - name: Clean up old docker files
      command: docker system prune -a -f
    - name: Pull and start docker compose
      #notify: restart voty
      community.docker.docker_compose_v2:
        pull: always
        project_src: "{{app_dir}}"
        state: present

    - name: Enable Web Backend Service
      service:
        { name: voty, enabled: yes, state: restarted, runlevel: "default" }
  become: yes
  become_method: sudo
