import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const src = readFileSync(
  join(process.cwd(), "pages/content/glossar.mdx"),
  "utf8",
);

const glossary: Record<string, string> = {};
let term = "";
for (const line of src.split("\n")) {
  const match = line.match(/^##\s+(.*)$/);
  if (match) {
    term = match[1].trim();
    glossary[term] = "";
  } else if (term && line.trim()) {
    glossary[term] = glossary[term]
      ? `${glossary[term]} ${line.trim()}`
      : line.trim();
  }
}

const out = `// Generated by scripts/gen-glossary.ts — do not edit by hand.
// Run \`yarn gen:glossary\` after editing pages/content/glossar.mdx.
export const glossaryData: Record<string, string> = ${JSON.stringify(glossary, null, 2)};
`;

writeFileSync(join(process.cwd(), "util/glossar-data.ts"), out);
process.stdout.write(
  `wrote util/glossar-data.ts (${Object.keys(glossary).length} terms)\n`,
);
